# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 776)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_tab_widget = QtWidgets.QTabWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab_widget.sizePolicy().hasHeightForWidth())
        self.main_tab_widget.setSizePolicy(sizePolicy)
        self.main_tab_widget.setObjectName("main_tab_widget")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.settings_tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1081, 681))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sub_settings = QtWidgets.QTabWidget(self.verticalLayoutWidget_4)
        self.sub_settings.setObjectName("sub_settings")
        self.sett_import = QtWidgets.QWidget()
        self.sett_import.setObjectName("sett_import")
        self.formLayoutWidget = QtWidgets.QWidget(self.sett_import)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1041, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName("formLayout")
        self.but_import_dir = QtWidgets.QPushButton(self.formLayoutWidget)
        self.but_import_dir.setObjectName("but_import_dir")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.but_import_dir)
        self.import_dir = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.import_dir.setEnabled(False)
        self.import_dir.setObjectName("import_dir")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.import_dir)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 700, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cb_file_type = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_file_type.setCurrentText("")
        self.cb_file_type.setObjectName("cb_file_type")
        self.horizontalLayout_4.addWidget(self.cb_file_type)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 500, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_date_format = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_date_format.setObjectName("cb_date_format")
        self.horizontalLayout_3.addWidget(self.cb_date_format)
        self.date_format = QtWidgets.QLabel(self.formLayoutWidget)
        self.date_format.setObjectName("date_format")
        self.horizontalLayout_3.addWidget(self.date_format)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.but_import = QtWidgets.QPushButton(self.sett_import)
        self.but_import.setGeometry(QtCore.QRect(920, 590, 111, 29))
        self.but_import.setObjectName("but_import")
        self.data_preview_tab = QtWidgets.QTableWidget(self.sett_import)
        self.data_preview_tab.setGeometry(QtCore.QRect(240, 130, 811, 261))
        self.data_preview_tab.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.data_preview_tab.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.data_preview_tab.setObjectName("data_preview_tab")
        self.data_preview_tab.setColumnCount(0)
        self.data_preview_tab.setRowCount(0)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.sett_import)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 130, 221, 301))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.date_col = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.date_col.setObjectName("date_col")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.date_col)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.description_col = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.description_col.setObjectName("description_col")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.description_col)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.amount_col = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.amount_col.setObjectName("amount_col")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.amount_col)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.balance_col = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.balance_col.setObjectName("balance_col")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.balance_col)
        self.sub_settings.addTab(self.sett_import, "")
        self.sett_categories = QtWidgets.QWidget()
        self.sett_categories.setObjectName("sett_categories")
        self.sett_category_aliases_tab = QtWidgets.QTableWidget(self.sett_categories)
        self.sett_category_aliases_tab.setGeometry(QtCore.QRect(10, 10, 351, 441))
        self.sett_category_aliases_tab.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.sett_category_aliases_tab.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sett_category_aliases_tab.setObjectName("sett_category_aliases_tab")
        self.sett_category_aliases_tab.setColumnCount(0)
        self.sett_category_aliases_tab.setRowCount(0)
        self.sett_categories_tab = QtWidgets.QTableWidget(self.sett_categories)
        self.sett_categories_tab.setGeometry(QtCore.QRect(370, 10, 691, 441))
        self.sett_categories_tab.setObjectName("sett_categories_tab")
        self.sett_categories_tab.setColumnCount(0)
        self.sett_categories_tab.setRowCount(0)
        self.sett_categories_unknown_tab = QtWidgets.QTableWidget(self.sett_categories)
        self.sett_categories_unknown_tab.setGeometry(QtCore.QRect(10, 460, 1051, 171))
        self.sett_categories_unknown_tab.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sett_categories_unknown_tab.setObjectName("sett_categories_unknown_tab")
        self.sett_categories_unknown_tab.setColumnCount(0)
        self.sett_categories_unknown_tab.setRowCount(0)
        self.sub_settings.addTab(self.sett_categories, "")
        self.verticalLayout_8.addWidget(self.sub_settings)
        self.main_tab_widget.addTab(self.settings_tab, "")
        self.overview_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overview_tab.sizePolicy().hasHeightForWidth())
        self.overview_tab.setSizePolicy(sizePolicy)
        self.overview_tab.setObjectName("overview_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.overview_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.overview_graph_hbox = QtWidgets.QHBoxLayout()
        self.overview_graph_hbox.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.overview_graph_hbox.setObjectName("overview_graph_hbox")
        self.verticalLayout.addLayout(self.overview_graph_hbox)
        self.month_graph_hbox = QtWidgets.QHBoxLayout()
        self.month_graph_hbox.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.month_graph_hbox.setObjectName("month_graph_hbox")
        self.verticalLayout.addLayout(self.month_graph_hbox)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.main_tab_widget.addTab(self.overview_tab, "")
        self.days_tab = QtWidgets.QWidget()
        self.days_tab.setObjectName("days_tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.days_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1071, 691))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.days_main_tab = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.days_main_tab.sizePolicy().hasHeightForWidth())
        self.days_main_tab.setSizePolicy(sizePolicy)
        self.days_main_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.days_main_tab.setObjectName("days_main_tab")
        self.overall_expenses = QtWidgets.QWidget()
        self.overall_expenses.setObjectName("overall_expenses")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.overall_expenses)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.day_expenses_vbox = QtWidgets.QVBoxLayout()
        self.day_expenses_vbox.setObjectName("day_expenses_vbox")
        self.horizontalLayout_2.addLayout(self.day_expenses_vbox)
        self.days_main_tab.addTab(self.overall_expenses, "")
        self.balance_tab = QtWidgets.QWidget()
        self.balance_tab.setObjectName("balance_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.balance_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.balance_vbox = QtWidgets.QVBoxLayout()
        self.balance_vbox.setObjectName("balance_vbox")
        self.verticalLayout_5.addLayout(self.balance_vbox)
        self.days_main_tab.addTab(self.balance_tab, "")
        self.horizontalLayout_5.addWidget(self.days_main_tab)
        self.main_tab_widget.addTab(self.days_tab, "")
        self.categories_tab = QtWidgets.QWidget()
        self.categories_tab.setObjectName("categories_tab")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.categories_tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 1071, 691))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.single_categories_container = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.single_categories_container.setObjectName("single_categories_container")
        self.main_tab_widget.addTab(self.categories_tab, "")
        self.search_tab = QtWidgets.QWidget()
        self.search_tab.setObjectName("search_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.search_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(500, -1, -1, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.search_tab)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.search_field = QtWidgets.QLineEdit(self.search_tab)
        self.search_field.setObjectName("search_field")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.search_field)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.search_results = QtWidgets.QTableWidget(self.search_tab)
        self.search_results.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.search_results.setObjectName("search_results")
        self.search_results.setColumnCount(0)
        self.search_results.setRowCount(0)
        self.verticalLayout_3.addWidget(self.search_results)
        self.main_tab_widget.addTab(self.search_tab, "")
        self.horizontalLayout.addWidget(self.main_tab_widget)
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_tab_widget.setCurrentIndex(0)
        self.sub_settings.setCurrentIndex(0)
        self.days_main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Expenses Visualizer"))
        self.but_import_dir.setText(_translate("MainWindow", "Import directory"))
        self.label_3.setText(_translate("MainWindow", "File type"))
        self.label_8.setText(_translate("MainWindow", "Date format"))
        self.date_format.setText(_translate("MainWindow", "TextLabel"))
        self.but_import.setText(_translate("MainWindow", "Import"))
        self.label_4.setText(_translate("MainWindow", "Date"))
        self.label_5.setText(_translate("MainWindow", "Description"))
        self.label_6.setText(_translate("MainWindow", "Amount"))
        self.label_7.setText(_translate("MainWindow", "Balance"))
        self.sub_settings.setTabText(self.sub_settings.indexOf(self.sett_import), _translate("MainWindow", "Import"))
        self.sett_category_aliases_tab.setSortingEnabled(False)
        self.sett_categories_tab.setSortingEnabled(False)
        self.sub_settings.setTabText(self.sub_settings.indexOf(self.sett_categories), _translate("MainWindow", "Manage categories"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.overview_tab), _translate("MainWindow", "Overview"))
        self.days_main_tab.setTabText(self.days_main_tab.indexOf(self.overall_expenses), _translate("MainWindow", "Overall expenses"))
        self.days_main_tab.setTabText(self.days_main_tab.indexOf(self.balance_tab), _translate("MainWindow", "Balanace"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.days_tab), _translate("MainWindow", "Days"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.categories_tab), _translate("MainWindow", "Categories"))
        self.label.setText(_translate("MainWindow", "Search"))
        self.search_results.setSortingEnabled(True)
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.search_tab), _translate("MainWindow", "Search"))

